insert into public.legal_decisions (
  decision_id,
  source_url,
  source_dataset,
  source_attribution,
  case_number,
  proceeding_number,
  court_name,
  court_region,
  court_level,
  decision_date,
  registration_date,
  proceeding_type,
  decision_type,
  text,
  cited_articles,
  cited_article_keys,
  cited_laws,
  outcome_label,
  outcome_confidence,
  key_excerpts,
  indexed_at
) values
(
  'sample-001',
  'https://reyestr.court.gov.ua/Review/sample-001',
  'synthetic-edrsr-sample',
  'Synthetic development sample, not a real court decision.',
  '910/1001/26',
  '',
  'Господарський суд міста Києва',
  'м. Київ',
  'first_instance',
  '2026-02-12',
  '2026-02-13',
  'commercial',
  'rishennia',
  'Позивач просив стягнути заборгованість, інфляційні втрати та 3 проценти річних за ст. 625 ЦК України. Суд встановив прострочення виконання грошового зобов''язання. Позов задовольнити частково.',
  array['625 ЦК України'],
  array['ЦК України:625'],
  array['ЦК України'],
  'partially_satisfied',
  0.91,
  array['ст. 625 ЦК України','Позов задовольнити частково'],
  '2026-06-06T00:00:00.000Z'
)
on conflict (decision_id) do nothing;
